### ISSUE TITLE
Issue with testing

### ISSUE THREAD

**Issue by clayne11** [gadicc/meteor-hmr#100]
When I try to test with mocha I get the following issue.

Test command:
`meteor test --settings private/dev/test-settings.json --driver-package=practicalmeteor:mocha`

Result:
```
W20160531-18:24:39.531(-4)? (STDERR) /Users/clayne/.meteor/packages/meteor-tool/.1.3.2_4.lbyo5v++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:267
W20160531-18:24:39.531(-4)? (STDERR)            				throw(ex);
W20160531-18:24:39.531(-4)? (STDERR)            				      ^
W20160531-18:24:39.634(-4)? (STDERR) TypeError: Arguments to path.join must be strings
W20160531-18:24:39.634(-4)? (STDERR)     at path.js:360:15
W20160531-18:24:39.634(-4)? (STDERR)     at Array.filter (/Users/clayne/.meteor/packages/es5-shim/.4.5.10.1kbbq1q++os+web.browser+web.cordova/npm/node_modules/es5-shim/es5-shim.js:499:48)
W20160531-18:24:39.634(-4)? (STDERR)     at Object.exports.join (path.js:358:36)
W20160531-18:24:39.634(-4)? (STDERR)     at Object.MeteorFilesHelpers.getPackageVersions (packages/sanjo_meteor-files-helpers/meteor_files_helpers.js:84:1)
W20160531-18:24:39.634(-4)? (STDERR)     at Object.getPackageVersions (packages/underscore/underscore.js:665:1)
W20160531-18:24:39.634(-4)? (STDERR)     at Object.MeteorFilesHelpers.getPackageVersion (packages/sanjo_meteor-files-helpers/meteor_files_helpers.js:100:1)
W20160531-18:24:39.635(-4)? (STDERR)     at Package (packages/gadicc_babel-compiler-babelrc/hotVersionCheck.js:14:1)
```

**Comment by gadicc** [comment]
Thanks.  Looking forward to getting rid of babel-compiler-babelrc :)  There's some similar code in some of the other files that I'll double check though.  It's weird that I did actually test test mode before making that release, but I guess it's one of those annoying things that behave differently with local packages.

**Comment by clayne11** [comment]
Potentially yeah. I am doing app testing, not package testing, but the local packages could potentially still be affecting it.

**Comment by gadicc** [comment]
Yeah, in app test mode Meteor runs your app in a temporary directory, only copies app files (and not `.meteor`, or at least, definitely not `.meteor/versions`) and doesn't provide anyway to know what the real project directory is.  So I must just disable this check in test mode.  Which I actually did already, but obviously I missed something :D

**Comment by gadicc** [comment]
I think I fixed this but rushing to get ready for a weekend away and don't have enough time to test properly / publish.  If you're running from master you can let me know if it solves the problem for you :D

**Comment by clayne11** [comment]
I've actually moved to Meteor `1.3.3`. Does `beta.4` work with the `1.3.3` beta? If so I'll try running from master.

**Comment by gadicc** [comment]
Yup!  You should also remove the meteor preset from your babelrc to make sure you're only using the new one from Meteor 1.3.3 which is included automatically. 

On 03 June 2016 7:41:38 PM SAST, Curtis Layne <notifications@github.com> wrote:
>I've actually moved to Meteor `1.3.3`. Does `beta.4` work with the
>`1.3.3` beta? If so I'll try running from master.
>
>---
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/gadicc/meteor-hmr/issues/100#issuecomment-223644775

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by clayne11** [comment]
I tried but I couldn't get it to run. I guess I'll just wait until you publish something.

**Comment by gadicc** [comment]
Ok, thanks for trying.  I just published `gadicc:ecmascript-hot@2.0.0-beta.4` for Meteor 1.3.3... as per the updated README and Updating docs, you should remove meteor from your .babelrc presets and npm rm --save-dev babel-preset-meteor.

**Comment by clayne11** [comment]
Great. Yeah I've already made those changes. I'll try it out this morning.

**Comment by clayne11** [comment]
Still seeing the same issue as when I was trying to run from `master`.

```
[[[[[ ~/workspace/r3ntr_meteor ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Starting gadicc:hot-build Accelerator (9cs) on port 3002.

=> Errors prevented startup:

   While loading plugin `compile-ecmascript-hot` from package `gadicc:ecmascript-hot`:
   path.js:360:15: Arguments to path.join must be strings
   at path.js:360:15
   at Array.filter (native)
   at Object.exports.join (path.js:358:36)
   at findPackagePath (packages/gadicc_hot-build/hot-server.js:92:1)
   at getPluginPath (packages/gadicc_hot-build/hot-server.js:100:1)
   at new Hot (packages/gadicc_hot-build/hot-server.js:143:1)
   at Package (packages/compile-ecmascript-hot/plugin.js:4:1)
   at <runJavaScript-50>:58:4
   at <runJavaScript-50>:65:3


=> Your application has errors. Waiting for file change.
```

Looks like it's failing to find `.meteor` or `projRoot` or something along those lines.

**Comment by clayne11** [comment]
I ran from `master` and added some print statements:

```
=> Your application has errors. Waiting for file change.
=> Modified -- restarting.
METEOR_HOME for os.osx.x86_64                /
/Users/clayne/.meteor
name
gadicc:ecmascript-hot
version
undefined
=> Errors prevented startup:

   While loading plugin `compile-ecmascript-hot` from package `gadicc:ecmascript-hot`:
   path.js:360:15: Arguments to path.join must be strings
   at path.js:360:15
   at Array.filter (native)
   at Object.exports.join (path.js:358:36)
   at findPackagePath (packages/gadicc_hot-build/hot-server.js:98:1)
   at getPluginPath (packages/gadicc_hot-build/hot-server.js:106:1)
   at new Hot (packages/gadicc_hot-build/hot-server.js:149:1)
   at Package (packages/compile-ecmascript-hot/plugin.js:4:1)
   at <runJavaScript-100>:58:4
   at <runJavaScript-100>:65:3
```

Looks like the `version` is undefined.

**Comment by clayne11** [comment]
OK I was able to solve this - I had implied `gadicc:ecmascript-hot` in a Meteor package because when I was testing I was flipping back and forth between `ecmascript` and `gadicc:ecmascript-hot`. I was able to fix it by actually adding `gadicc:ecmascript-hot` directly to the app, not just implying it in a package.

**Comment by gadicc** [comment]
Ok,

1) Thanks for all the investigative work and glad you're up and running
2) This should still work without being part of the app, and just a package.  I'll have to look into this some more.

Leaving open until I can spend more time on this.

**Comment by clayne11** [comment]
Alright. The testing issue is fixed though, perhaps we should open a new issue with this new problem.

**Comment by gadicc** [comment]
Agreed :)

**Comment by neooleg** [comment]
Pls apologize me for a stupid questions. I'm recently started to use Meteor -- found some info about imply/use package, but still it isn't clear.

How to actually add `gadicc:ecmascript-hot` directly to the app, not just imply?
